### ISSUE TITLE
Slideshow overlay

### ISSUE THREAD

**Issue by maxwellito** [roshlarosh/roshlarosh.github.io#1]
The slideshow is passing over the nav bar while scrolling.

**Steps to reproduce**:
1. Scroll to the slideshow
2. Look at the nav bar

![Screenshot 2019-08-24 at 13 02 20](https://user-images.githubusercontent.com/1097232/63637919-a9918080-c671-11e9-9f87-44c5b4067ad5.png)

**Comment by roshlarosh** [comment]
**Issue fixed:** 
The image slider was overlapping the header, modified the z-order of the header element by adding z-index = 1
