### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by maxwellito** [roshlarosh/roshlarosh.github.io#3]
Platform icons in the footer are not linked to their respective website.
Maybe it's intentional.

**Steps to reproduce**:
1. Scroll down to the 'freeCodeCamp/CodeWars/GitHub' icons.
2. Nothing happen on clicks.

![Screenshot 2019-08-24 at 14 22 09](https://user-images.githubusercontent.com/1097232/63637997-7d2a3400-c672-11e9-93be-19d7f9ec0124.png)

**Comment by roshlarosh** [comment]
For now this is intentional. Will look into font awesome to make responsive icons.

**Comment by roshlarosh** [comment]
*Fixed*:
Added font awesome icons and made link clickable
