### ISSUE TITLE
⬇️Function call order

### ISSUE THREAD

**Issue by astroash** [roshlarosh/roshlarosh.github.io#5]
https://github.com/roshlarosh/roshlarosh.github.io/blob/4be412b0b65886389dd8ebbd53660b64c04d2ae4/image-slider.js#L13

Here you are calling a function before it is defined. This works because js hoists all functions to the top of the scope, however as a human this makes code hard to read because you are reading about a function being used before knowing what it does. 

It's best practice to write all of your functions before they are invoked. Here's a nice explanation: https://www.w3schools.com/js/js_hoisting.asp

**Comment by roshlarosh** [comment]
Makes sense, I have declared the function before calling it.
