### ISSUE TITLE
👹 double equals is the devil...

### ISSUE THREAD

**Issue by astroash** [roshlarosh/roshlarosh.github.io#6]
https://github.com/roshlarosh/roshlarosh.github.io/blob/4be412b0b65886389dd8ebbd53660b64c04d2ae4/image-slider.js#L21

double equals is the devil, it does type coercion, which is something you pretty much never want.

Check this article out: https://codeburst.io/javascript-double-equals-vs-triple-equals-61d4ce5a121a

**Comment by roshlarosh** [comment]
Learnt my lesson, changed to triple equals from now on.
